molecole_obj = [
    {"nome": "ACETILCISTEINA", "smiles": "CC(=O)N[C@@H](CS)C(=O)O"},
    {"nome": "ACIDO ACETILSALICILICO", "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O"},
    {"nome": "ACIDO ASCORBICO", "smiles": "C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O"},
    {"nome": "ACIDO BENZOICO", "smiles": "C1=CC=C(C=C1)C(=O)O"},
    {"nome": "ACIDO CITRICO", "smiles": "C(C(=O)O)C(CC(=O)O)(C(=O)O)O"},
    {"nome": "ACIDO NICOTINICO", "smiles": "C1=CC(=CN=C1)C(=O)O"},
    {"nome": "ACIDO SALICILICO", "smiles": "C1=CC=C(C(=C1)C(=O)O)O"},
    {"nome": "ACIDO SORBICO", "smiles": "C/C=C/C=C/C(=O)O"},
    {"nome": "ACIDO TANNICO", "smiles": "C1=C(C=C(C(=C1O)O)O)C(=O)OC2=CC(=CC(=C2O)O)C(=O)OC[C@@H]3[C@H]([C@@H]([C@H](C(O3)OC(=O)C4=CC(=C(C(=C4)OC(=O)C5=CC(=C(C(=C5)O)O)O)O)O)OC(=O)C6=CC(=C(C(=C6)OC(=O)C7=CC(=C(C(=C7)O)O)O)O)O)OC(=O)C8=CC(=C(C(=C8)OC(=O)C9=CC(=C(C(=C9)O)O)O)O)O)OC(=O)C1=CC(=C(C(=C1)OC(=O)C1=CC(=C(C(=C1)O)O)O)O)O"},
    {"nome": "ACIDO TARTARICO", "smiles": "[C@H]([C@@H](C(=O)O)O)(C(=O)O)O"},
    {"nome": "ALANINA", "smiles": "C[C@@H](C(=O)O)N"},
    {"nome": "ASPARTAME", "smiles": "COC(=O)[C@H](CC1=CC=CC=C1)NC(=O)[C@H](CC(=O)O)N"},
    {"nome": "BENZOCAINA", "smiles": "CCOC(=O)C1=CC=C(C=C1)N"},
    {"nome": "CAFFEINA", "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C"},
    {"nome": "CALCIO GLICEROFOSFATO", "smiles": "C(C(CO)OP(=O)([O-])[O-])O.[Ca+2]"},
    {"nome": "CALCIO GLUCONATO", "smiles": "C([C@H]([C@H]([C@@H]([C@H](C(=O)[O-])O)O)O)O)O.C([C@H]([C@H]([C@@H]([C@H](C(=O)[O-])O)O)O)O)O.[Ca+2]"},
    {"nome": "CALCIO LATTATO", "smiles": "CC(C(=O)[O-])O.CC(C(=O)[O-])O.[Ca+2]"},
    {"nome": "CALCIO PANTOTENATO", "smiles": "CC(C)(CO)[C@H](C(=O)NCCC(=O)[O-])O.CC(C)(CO)[C@H](C(=O)NCCC(=O)[O-])O.[Ca+2]"},
    {"nome": "CAPTOPRIL", "smiles": "C[C@H](CS)C(=O)N1CCC[C@H]1C(=O)O"},
    {"nome": "CHINIDINA SOLFATO", "smiles": "COC1=CC2=C(C=CN=C2C=C1)[C@@H]([C@H]3C[C@@H]4CCN3C[C@@H]4C=C)O.[SO4]2-"},
    {"nome": "CHININA HCl", "smiles": "COC1=CC2=C(C=CN=C2C=C1)[C@H]([C@@H]3C[C@@H]4CCN3C[C@@H]4C=C)O"},
    {"nome": "CHININA SOLFATO", "smiles": "COC1=CC2=C(C=CN=C2C=C1)[C@H]([C@@H]3C[C@@H]4CCN3C[C@@H]4C=C)O"},
    {"nome": "CISTEINA HCl", "smiles": "C([C@@H](C(=O)O)N)S"},
    {"nome": "CLORALIO IDRATO", "smiles": "C(C(Cl)(Cl)Cl)(O)O"},
    {"nome": "CLORAMINA T", "smiles": "CC1=CC=C(C=C1)S(=O)(=O)[N-]Cl.[Na+]"},
    {"nome": "CLORBUTANOLO", "smiles": "CC(C)(C(Cl)(Cl)Cl)O"},
    {"nome": "CLOROCHINA BIFOSFATO", "smiles": "CCN(CC)CCCC(C)NC1=C2C=CC(=CC2=NC=C1)Cl "},
    {"nome": "CLORPROMAZINA HCl", "smiles": "CN(C)CCCN1C2=CC=CC=C2SC3=C1C=C(C=C3)Cl"},
    {"nome": "CORTISONE ACETATO", "smiles": "CC(=O)OCC(=O)[C@]1(CC[C@@H]2[C@@]1(CC(=O)[C@H]3[C@H]2CCC4=CC(=O)CC[C@]34C)C)O"},
    {"nome": "DAPSONE", "smiles": "C1=CC(=CC=C1N)S(=O)(=O)C2=CC=C(C=C2)N"},
    {"nome": "DESAMETASONE ACETATO", "smiles": "C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)COC(=O)C)O)C)O)F)C"},
    {"nome": "DESAMETASONE SODIO FOSFATO", "smiles": "C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)COP(=O)([O-])[O-])O)C)O)F)C.[Na+].[Na+]"},
    {"nome": "DIFENIDRAMINA HCl", "smiles": "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2"},
    {"nome": "ECONAZOLO NITRATO", "smiles": "C1=CC(=CC=C1COC(CN2C=CN=C2)C3=C(C=C(C=C3)Cl)Cl)Cl.[N+](=O)(O)[O-]"},
    {"nome": "EFEDRINA HCl", "smiles": "C[C@@H]([C@@H](C1=CC=CC=C1)O)NC"},
    {"nome": "FENAZONE", "smiles": "CC1=CC(=O)N(N1C)C2=CC=CC=C2"},
    {"nome": "FENILALANINA", "smiles": "C1=CC=C(C=C1)C[C@@H](C(=O)O)N"},
    {"nome": "FENILEFRINA HCl", "smiles": "CNC[C@@H](C1=CC(=CC=C1)O)O"},
    {"nome": "FENOLO", "smiles": "C1=CC=C(C=C1)O"},
    {"nome": "FENOTIAZINA", "smiles": "C1=CC=C2C(=C1)NC3=CC=CC=C3S2"},
    {"nome": "FRUTTOSIO", "smiles": "1[C@H]([C@H]([C@@H](C(O1)(CO)O)O)O)O"},
    {"nome": "FTALILSULFATIAZOLO", "smiles": "C1=CC=C(C(=C1)C(=O)NC2=CC=C(C=C2)S(=O)(=O)NC3=NC=CS3)C(=O)O"},
    {"nome": "FUROSEMIDE", "smiles": ""},
    {"nome": "GLICINA", "smiles": ""},
    {"nome": "GLUCOSIO", "smiles": ""},
    {"nome": "IDROCLOROTIAZIDE", "smiles": ""},
    {"nome": "IDROCORTISONE", "smiles": ""},
    {"nome": "IDROCORTISONE ACETATO", "smiles": ""},
    {"nome": "IMIPRAMINA HCl", "smiles": ""},
    {"nome": "INDOMETACINA", "smiles": ""},
    {"nome": "ISONIAZIDE", "smiles": ""},
    {"nome": "LATTOSIO", "smiles": ""},
    {"nome": "LEUCINA", "smiles": ""},
    {"nome": "LIDOCAINA HCl", "smiles": ""},
    {"nome": "LISINA HCl", "smiles": ""},
    {"nome": "LITIO CITRATO", "smiles": ""},
    {"nome": "MAGNESIO ASPARTATO", "smiles": ""},
    {"nome": "MAGNESIO LATTATO", "smiles": ""},
    {"nome": "MANNITOLO", "smiles": ""},
    {"nome": "METFORMINA HCl", "smiles": ""},
    {"nome": "METILPARABEN", "smiles": ""},
    {"nome": "METIONINA", "smiles": ""},
    {"nome": "METRONIDAZOLO", "smiles": ""},
    {"nome": "NICLOSAMIDE", "smiles": ""},
    {"nome": "NICOTINAMIDE", "smiles": ""},
    {"nome": "NIFEDIPINA", "smiles": ""},
    {"nome": "PAPAVERINA HCl", "smiles": ""},
    {"nome": "PARACETAMOLO", "smiles": ""},
    {"nome": "PIRIDOSSINA HCl", "smiles": ""},
    {"nome": "POTASSIO ASPARTATO", "smiles": ""},
    {"nome": "POTASSIO CITRATO", "smiles": ""},
    {"nome": "POTASSIO SORBATO", "smiles": ""},
    {"nome": "POTASSIO TARTRATO", "smiles": ""},
    {"nome": "PREDNISONE", "smiles": ""},
    {"nome": "PROBENECID", "smiles": ""},
    {"nome": "PROCAINA HCl", "smiles": ""},
    {"nome": "PROCAINAMMIDE HCl", "smiles": ""},
    {"nome": "PROGESTERONE", "smiles": ""},
    {"nome": "PROLINA", "smiles": ""},
    {"nome": "PROMETAZINA HCl", "smiles": ""},
    {"nome": "PROPIFENAZONE", "smiles": ""},
    {"nome": "PROPILPARABEN", "smiles": ""},
    {"nome": "SACCARINA", "smiles": ""},
    {"nome": "SACCARINA SODICA", "smiles": ""},
    {"nome": "SACCAROSIO", "smiles": ""},
    {"nome": "SCOPOLAMINA HBr", "smiles": ""},
    {"nome": "SERINA", "smiles": ""},
    {"nome": "SODIO ACETATO", "smiles": ""},
    {"nome": "SODIO ASCORBATO", "smiles": ""},
    {"nome": "SODIO BENZOATO", "smiles": ""},
    {"nome": "SODIO CITRATO", "smiles": ""},
    {"nome": "SODIO P-AMMINO SALICILATO", "smiles": ""},
    {"nome": "SODIO SALICILATO", "smiles": ""},
    {"nome": "SORBITOLO", "smiles": ""},
    {"nome": "SPIRONOLATTONE", "smiles": ""},
    {"nome": "SUCRALOSIO", "smiles": ""},
    {"nome": "SULFADIAZINA", "smiles": ""},
    {"nome": "SULFAGUANIDINA", "smiles": ""},
    {"nome": "SULFAMERAZINA", "smiles": ""},
    {"nome": "SULFAMETOSSIPIRIDAZINA", "smiles": ""},
    {"nome": "SULFANILAMIDE", "smiles": ""},
    {"nome": "SULFATIAZOLO", "smiles": ""},
    {"nome": "TEOBROMINA", "smiles": ""},
    {"nome": "TEOFILLINA", "smiles": ""},
    {"nome": "TIAMINA HCl", "smiles": ""},
    {"nome": "TIMOLO", "smiles": ""},
    {"nome": "TOLBUTAMIDE", "smiles": ""},
    {"nome": "TREONINA", "smiles": ""},
    {"nome": "TRIPTOFANO", "smiles": ""},
    {"nome": "VALINA", "smiles": ""},
    {"nome": "VANILLINA", "smiles": ""}
]
